from collections import namedtuple
from itertools import combinations_with_replacement, permutations, chain
import numba as nb
import jax.numpy as jnp
import numpy as np
from jax.ops import segment_sum

OneDNodesAndWeights = namedtuple("OneDNodesAndWeights", ['level', 'roots', 'weights'])


def one_d_difference_grid(one_d_nodes_and_weights_list: list) \
        -> list[OneDNodesAndWeights]:
    """
    Takes a list of 1D nodes and their weights and create difference grid nodes and weights.
    The difference between each level is generated by subtracting from previous level.

    Parameters
    ----------
    one_d_nodes_and_weights_list : list
        List of OneDNodesAndWeights containing 1D nodes and weights at each level.
        Each element contains level number, roots (grid points) and weights.

    Returns
    -------
    list[OneDNodesAndWeights]
        List of OneDNodesAndWeights namedtuples containing the difference grid nodes and weights.
        Each element contains level number, roots (grid points) and delta weights.
    """
    difference_grids = []
    isin = np.isin

    for i in range(len(one_d_nodes_and_weights_list)):
        ondrw = one_d_nodes_and_weights_list[i]
        if ondrw.level == 1:
            difference_grids.append(one_d_nodes_and_weights_list[i])
        else:
            ondrw_m_1 = one_d_nodes_and_weights_list[i - 1]
            similar_roots_flags = isin(ondrw.roots, ondrw_m_1.roots)
            if np.any(similar_roots_flags):
                similar_roots = ondrw.roots[similar_roots_flags]

                # although the root positions are the same, but the weight are different
                similar_weights = ondrw.weights[similar_roots_flags] - ondrw_m_1.weights[
                    ondrw_m_1.roots == similar_roots]
            else:
                similar_roots = np.array([])
                similar_weights = np.array([])

            current_roots = ondrw.roots[~ similar_roots_flags]
            current_weights = ondrw.weights[~ similar_roots_flags]

            similar_roots_flags = isin(ondrw_m_1.roots, ondrw.roots)
            prev_roots = ondrw_m_1.roots[~ similar_roots_flags]
            prev_weights = - ondrw_m_1.weights[~ similar_roots_flags]  # this is minus

            delta_weights = np.concatenate((current_weights, prev_weights, similar_weights))
            delta_roots = np.concatenate((current_roots, prev_roots, similar_roots))

            difference_grids.append(OneDNodesAndWeights(ondrw.level, delta_roots, delta_weights))

    return difference_grids


def smolyak_indices(dim: int, max_level: int) -> np.ndarray:
    """
    Takes dimension and maximum level as input to return array with smolyak indices.
    A smolyak grid is a sparse grid for high dimensional interpolation or integration.
    This function calculates the indices used for constructing the smolyak grid.

    Parameters
    ----------
    dim : int
        The dimension of the grid.
    max_level : int
        The maximum level of the grid. Higher levels give more accuracy but more points.

    Returns
    -------
    np.array
        Array containing the smolyak indices. Each row represents one index set.
        The indices are used to select nodes and weights when constructing the full grid.
    """
    # Need to capture up to value mu + 1 so in python need mu+2
    possible_values = range(1, max_level + 1)

    # find all (i1, i2, ... id) such that their sum is in range
    # we want; this will cut down on later iterations
    raw_indices = np.array(list(combinations_with_replacement(possible_values, dim)))

    # limit the indices only to those satisfies the bound
    poss_indices = raw_indices[np.sum(raw_indices, axis=1) < dim + max_level]

    # use set to remove duplicate entries.
    true_inds = [[el for el in set(permutations(val))] for val in poss_indices]

    return np.array(list(chain(*true_inds)))


def get_raw_grids(smol_indices: np.ndarray, difference_grids: list[OneDNodesAndWeights]) -> tuple[
    np.ndarray, np.ndarray]:
    """
    Creates the raw Smolyak grid points and their weights from the input indices and basic difference grids.
    This is an intermediate step in constructing the full Smolyak grid, generating raw points and weights
    before combining duplicates.

    Parameters
    ----------
    smol_indices : np.ndarray
        Array of Smolyak indices used to select nodes and weights.
        Each row represents one index set for a particular dimension.
    difference_grids : list[OneDNodesAndWeights]
        List of OneDNodesAndWeights namedtuples containing the difference grid nodes and weights.
        Each element contains level number, roots (grid points) and delta weights.

    Returns
    -------
    tuple[np.ndarray, np.ndarray]
        raw_grid_points : Array of raw grid points before combining duplicates
        raw_weights : Array of weights corresponding to the raw grid points

    """
    dim = smol_indices.shape[1]

    raw_grid_points = []
    raw_weights = []
    for indices in smol_indices:
        one_d_grids = []
        one_d_weights = []
        number_of_elements = 1
        for index in indices:
            roots = difference_grids[index - 1].roots
            weights = difference_grids[index - 1].weights
            one_d_grids.append(roots)
            one_d_weights.append(weights)
            number_of_elements *= roots.shape[0]

        grids = np.stack(np.meshgrid(*one_d_grids), axis=-1)
        grids = grids.reshape((number_of_elements, dim))
        nd_weights = np.stack(np.meshgrid(*one_d_weights), axis=-1)
        nd_weights = np.prod(nd_weights.reshape((number_of_elements, dim)), axis=-1)

        raw_grid_points.append(grids)
        raw_weights.append(nd_weights)

    raw_grid_points = np.vstack(raw_grid_points) #np.stack(list(chain(*raw_grid_points)))
    raw_weights = np.hstack(raw_weights).squeeze() #np.stack(list(chain(*raw_weights)))
    return raw_grid_points, raw_weights


def single_out(raw_grid_points: np.ndarray, raw_weights: np.ndarray) -> tuple[np.ndarray, np.ndarray]:

    """
    Takes raw grid points and weights and combines duplicates by summing their weights.
    [gather all similar grid points and sum all their weights.]
    This function processes the raw grid points and weights produced by the Smolyak grid construction,
    finding unique grid points and summing the weights of any duplicate points.

    Parameters
    ----------
    raw_grid_points : np.ndarray
        Array of raw grid points, possibly containing duplicates
        Shape is (n_points, dimension)
    raw_weights : np.ndarray
        Array of weights corresponding to raw grid points
        Shape is (n_points,)

    Returns
    -------
    tuple[np.ndarray, np.ndarray]
        _unique_grid_points : Array of unique grid points with duplicates removed
        _unique_weights : Array of combined weights for unique grid points
    """
    unique_grid_points, indices = jnp.unique(raw_grid_points, axis=0, return_inverse=True)
    unique_weights = segment_sum(raw_weights.squeeze(), indices.squeeze(), num_segments=unique_grid_points.shape[0])
    return unique_grid_points, unique_weights



def smolyak_grid(dim: int, one_d_nodes_and_weights_list: list, weight_cut_off: float = None):
    """
    Constructs a Smolyak grid for high-dimensional interpolation or integration.

    This function uses a naive numpy-based approach to construct a Smolyak grid,
    which is a sparse grid technique for high-dimensional problems.
    The implementation is suitable for low-dimensional cases.

    Parameters
    ----------
    dim : int
        The dimension of the grid
    one_d_nodes_and_weights_list : list
        List of OneDNodesAndWeights containing 1D nodes and weights at each level.
        Each element contains level number, roots (grid points) and weights.
    weight_cut_off : float, optional
        Threshold for removing grid points with weights close to zero.
        Points with absolute weights below this value are excluded.

    Returns
    -------
    tuple[np.ndarray, np.ndarray, np.ndarray]
        smol_indices : Array of Smolyak indices used to construct the grid
        unique_grid_points : Array of unique grid points after removing duplicates
        unique_weights : Array of weights corresponding to unique grid points

    Notes
    -----
    The Smolyak grid construction involves:
    1. Creating difference grids from 1D nodes and weights
    2. Generating Smolyak indices for the given dimension
    3. Creating raw grid points and weights
    4. Combining duplicate points and summing their weights
    5. Optionally removing points with negligible weights
    """

    difference_grids = one_d_difference_grid(one_d_nodes_and_weights_list)
    max_level = len(difference_grids)
    smol_indices = smolyak_indices(dim, max_level)
    raw_grid_points, raw_weights = get_raw_grids(smol_indices, difference_grids)
    # gather similar points, and accumulate their weights

    unique_grid_points, unique_weights = single_out(raw_grid_points, raw_weights)

    if weight_cut_off:
        # remove those that has zero weights, or close to zero
        flags = np.isclose(np.abs(unique_weights), 0, rtol=weight_cut_off)
        unique_weights = unique_weights[~ flags]
        unique_grid_points = unique_grid_points[~ flags]

    return smol_indices, unique_grid_points, unique_weights
